# Generated by Django 2.2.16 on 2022-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220616_1848'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_follow'),
        ),
    ]
